/**
 * One-off ETL: serialize the mock demo tenant ("Douala General Hospital") into a
 * Postgres seed.sql for Supabase. Friendly string IDs (e.g. "hosp_demo") are
 * remapped to UUIDs across every collection and foreign key, so the result is a
 * faithful copy of the current mock dataset that the live app (UUID PKs) accepts.
 *
 * Run: tsx scripts/seed-demo.ts > supabase/seed.sql
 */

// --- Browser polyfills so mockStorage's persist/reload branch runs in node ----
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
// NOTE: mockStorage only checks `typeof window` at call time (not import time),
// so a hoisted static import is safe as long as the polyfill is set before we
// CALL resetDatabase() below.
import { resetDatabase } from "../services/mockStorage";

class MemoryStorage {
  private store = new Map<string, string>();
  get length() {
    return this.store.size;
  }
  getItem(k: string) {
    return this.store.has(k) ? this.store.get(k)! : null;
  }
  setItem(k: string, v: string) {
    this.store.set(k, String(v));
  }
  removeItem(k: string) {
    this.store.delete(k);
  }
  clear() {
    this.store.clear();
  }
  key(i: number) {
    return Array.from(this.store.keys())[i] ?? null;
  }
}
const mem = new MemoryStorage();
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(globalThis as any).window = { localStorage: mem };
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(globalThis as any).localStorage = mem;

// --- DB column whitelist (read from /tmp/cols.txt: "table|c1,c2,...") ----------
const cols = new Map<string, string[]>();
for (const line of readFileSync("/tmp/cols.txt", "utf8").trim().split("\n")) {
  const [table, list] = line.split("|");
  cols.set(table, list.split(","));
}

// --- mock collection key -> DB table name -------------------------------------
const TABLE: Record<string, string> = {
  hospitals: "hospitals",
  departments: "departments",
  wards: "wards",
  beds: "beds",
  staff: "staff",
  patients: "patients",
  allergies: "allergies",
  visits: "visits",
  consultations: "consultations",
  diagnoses: "diagnoses",
  orders: "orders",
  results: "results",
  prescriptions: "prescriptions",
  medicationAdministrations: "medication_administrations",
  treatmentRecords: "treatment_records",
  admissions: "admissions",
  transfers: "transfers",
  carePlanItems: "care_plan_items",
  carePlanEntries: "care_plan_entries",
};

// Insert order: parents before children (clean even though we disable FK checks).
const ORDER = [
  "hospitals",
  "departments",
  "wards",
  "staff",
  "patients",
  "allergies",
  "visits",
  "consultations",
  "diagnoses",
  "orders",
  "results",
  "prescriptions",
  "medicationAdministrations",
  "treatmentRecords",
  "admissions",
  "beds", // beds.current_admission_id -> admissions (circular); emit after admissions
  "transfers",
  "carePlanItems",
  "carePlanEntries",
];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = resetDatabase() as unknown as Record<string, any[]>;

// --- Build a global friendly-id -> uuid map across every collection -----------
const idMap = new Map<string, string>();
for (const key of Object.keys(TABLE)) {
  for (const row of db[key] ?? []) {
    if (typeof row.id === "string" && !idMap.has(row.id)) {
      idMap.set(row.id, randomUUID());
    }
  }
}

const sqlQuote = (s: string) => "'" + s.replace(/'/g, "''") + "'";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function formatValue(col: string, val: any): string {
  // auth.users link does not exist in a fresh project -> always null.
  if (col === "user_id") return "NULL";
  if (val === null || val === undefined) return "NULL";
  // Remap PK / FK columns (id or *_id) when the value is a known friendly id.
  if ((col === "id" || col.endsWith("_id")) && typeof val === "string") {
    const mapped = idMap.get(val);
    if (mapped) return sqlQuote(mapped);
    // Not a known id (e.g. national_id) -> emit literally below.
  }
  if (typeof val === "boolean") return val ? "true" : "false";
  if (typeof val === "number") return String(val);
  return sqlQuote(String(val));
}

const out: string[] = [];
out.push("-- CareFlow demo seed (generated by scripts/seed-demo.ts). DO NOT edit by hand.");
out.push("begin;");
out.push("set session_replication_role = replica; -- disable FK triggers during load");
out.push("");

let total = 0;
for (const key of ORDER) {
  const table = TABLE[key];
  const allowed = cols.get(table);
  if (!allowed) throw new Error(`No column info for table ${table}`);
  const rows = db[key] ?? [];
  if (rows.length === 0) continue;
  out.push(`-- ${table} (${rows.length})`);
  for (const row of rows) {
    const usedCols: string[] = [];
    const vals: string[] = [];
    for (const col of allowed) {
      if (!(col in row)) continue; // let DB default apply
      usedCols.push(col);
      vals.push(formatValue(col, row[col]));
    }
    out.push(
      `insert into ${table} (${usedCols.join(", ")}) values (${vals.join(", ")});`,
    );
    total++;
  }
  out.push("");
}

out.push("set session_replication_role = origin;");
out.push("commit;");
out.push(`-- total rows: ${total}`);

process.stdout.write(out.join("\n") + "\n");
process.stderr.write(`Generated ${total} rows across ${ORDER.length} tables.\n`);
